// PRODUCTS 
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"


