const API_URL = import.meta.env.VITE_API_URL;
const LOCAL_API_URL = import.meta.env.VITE_LOCAL_API_URL;
const WEBSOCKET_URL = import.meta.env.VITE_WEBSOCKET_URL;
const WEBSOCKET_LOCAL_URL = import.meta.env.VITE_WEBSOCKET_LOCAL_URL;
const GOOGLE_AUTH_URL = import.meta.env.VITE_GOOGLE_AUTH_URL;

export { API_URL, LOCAL_API_URL, WEBSOCKET_URL, WEBSOCKET_LOCAL_URL, GOOGLE_AUTH_URL };
