name: Github actions tests
run-name: ${{ github.actor }} contributes to ${{ github.repository }}
on:
  push:
    branches:
      - '**'

jobs:
  github_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_LOCAL_API_URL: ${{ secrets.VITE_LOCAL_API_URL }}
          VITE_WEBSOCKET_URL: ${{ secrets.VITE_WEBSOCKET_URL }}
          VITE_WEBSOCKET_LOCAL_URL: ${{ secrets.VITE_WEBSOCKET_LOCAL_URL }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
          VITE_CLOUDINARY_API_KEY: ${{ secrets.VITE_CLOUDINARY_API_KEY }}
          VITE_CLOUDINARY_API_SECRET: ${{ secrets.VITE_CLOUDINARY_API_SECRET }}
        run: |
          npm run coverage
